export const InternalCategories = {
  'Fashion/Women': 2,
  'Fashion/Women/Clothing': 3,
  'Fashion/Women/Clothing/Tailoring': 4,
  'Fashion/Women/Clothing/Tailoring/Suit Trousers': 5,
  'Fashion/Women/Bags': 6,
  'Fashion/Women/Bags/Luggage': 7,
  'Fashion/Men': 8,
  'Fashion/Men/Activewear': 9,
  'Fashion/Men/Activewear/Performance Jackets': 10,
  'Fashion/Men/Activewear/Performance Jackets/Performance Track Jackets': 11,
  'Fashion/Men/Shoes': 12,
  'Fashion/Men/Shoes/Sneakers': 13,
  'Fashion/Men/Shoes/Sneakers/Hi-Tops': 14,
  'Fashion/Men/Activewear/Skiwear': 15,
  'Fashion/Men/Activewear/Skiwear/Ski Accessories': 16,
  'Fashion/Men/Bags': 17,
  'Fashion/Men/Bags/Beach Bags': 18,
  'Fashion/Women/Clothing/Knits': 19,
  'Fashion/Women/Clothing/Knits/Knitted Sweaters': 20,
  'Fashion/Women/Clothing/Knits/Knitted Trousers': 21,
  'Fashion/Women/Activewear': 22,
  'Fashion/Women/Activewear/Performance Tops': 23,
  'Fashion/Women/Activewear/Performance Accessories': 24,
  'Fashion/Women/Activewear/Performance Accessories/Helmets': 25,
  'Fashion/Men/Clothing': 26,
  'Fashion/Men/Clothing/Jackets': 27,
  'Fashion/Men/Clothing/Jackets/Biker Jackets': 28,
  'Fashion/Women/Lingerie & Nightwear': 29,
  'Fashion/Women/Lingerie & Nightwear/Nightwear': 30,
  'Fashion/Women/Lingerie & Nightwear/Nightwear/Dressing Gowns & Robes': 31,
  'Fashion/Women/Jewelry': 32,
  'Fashion/Women/Jewelry/Earrings': 33,
  'Fashion/Men/Clothing/Shorts': 34,
  'Fashion/Men/Clothing/Shorts/Deck Shorts': 35,
  'Fashion/Men/Shoes/Sandals': 36,
  'Fashion/Women/Shoes': 37,
  'Fashion/Women/Shoes/Shoe Accessories': 38,
  'Fashion/Women/Bags/Backpacks': 39,
  'Fashion/Men/Clothing/Pants': 40,
  'Fashion/Men/Clothing/Pants/Cropped Pants': 41,
  'Fashion/Women/Homeware': 42,
  'Fashion/Women/Homeware/Home Decor': 43,
  'Fashion/Women/Homeware/Home Decor/Decorative Trays & Plates': 44,
  'Fashion/Women/Shoes/Espadrilles': 45,
  'Fashion/Men/Clothing/Suits': 46,
  'Fashion/Men/Clothing/Coats': 47,
  'Fashion/Men/Clothing/Coats/Down Coats': 48,
  'Fashion/Women/Clothing/Knits/Cardi-Coats': 49,
  'Fashion/Men/Clothing/Pants/Sweatpants': 50,
  'Fashion/Men/Shoes/Flip Flops & Slides': 51,
  'Fashion/Men/Clothing/Swimwear': 52,
  'Fashion/Men/Clothing/Swimwear/Swimming Trunks': 53,
  'Fashion/Men/Homeware': 54,
  'Fashion/Men/Shoes/Lace-Up Shoes': 55,
  'Fashion/Women/Clothing/Denim': 56,
  'Fashion/Women/Clothing/Denim/Denim Skirts': 57,
  'Fashion/Men/Clothing/Pants/Wide Leg Pants': 58,
  'Fashion/Men/Activewear/Skiwear/Ski Jackets': 59,
  'Fashion/Women/Lingerie & Nightwear/Loungewear': 60,
  'Fashion/Women/Accessories': 61,
  'Fashion/Women/Accessories/Wallets & Purses': 62,
  'Fashion/Women/Homeware/Stationery': 63,
  'Fashion/Women/Activewear/Performance Accessories/Performance Eyewear': 64,
  'Fashion/Men/Shoes/Shoe Accessories': 65,
  'Fashion/Men/Homeware/Dining & Kitchen': 66,
  'Fashion/Men/Accessories': 67,
  'Fashion/Men/Underwear & Socks': 68,
  'Fashion/Men/Underwear & Socks/Socks': 69,
  'Fashion/Women/Clothing/Beachwear': 70,
  'Fashion/Women/Clothing/Beachwear/One-Pieces': 71,
  'Fashion/Men/Clothing/Polo Shirts': 72,
  'Fashion/Men/Accessories/Umbrellas': 73,
  'Fashion/Women/Bags/Laptop Bags': 74,
  'Fashion/Women/Activewear/Performance All-In-Ones': 75,
  'Fashion/Women/Activewear/Performance All-In-Ones/Leotards': 76,
  'Fashion/Women/Clothing/Skirts': 77,
  'Fashion/Women/Clothing/Skirts/High-Waisted Skirts': 78,
  'Fashion/Women/Lingerie & Nightwear/Socks': 79,
  'Fashion/Men/Accessories/Hats': 80,
  'Fashion/Men/Watches': 81,
  'Fashion/Men/Clothing/Jackets/Lightweight Jackets': 82,
  'Fashion/Women/Bags/Beach Bags': 83,
  'Fashion/Men/Activewear/Performance Accessories': 84,
  'Fashion/Men/Bags/Shoulder Bags': 85,
  'Fashion/Women/Bags/Tote Bags': 86,
  'Fashion/Men/Watches/Fine Watches': 87,
  'Fashion/Men/Watches/Fine Watches/Aviator Watches': 88,
  'Fashion/Men/Clothing/Jackets/Military Jackets': 89,
  'Fashion/Men/Shoes/Sneakers/Slip-On': 90,
  'Fashion/Men/Clothing/Shorts/Track & Running Shorts': 91,
  'Fashion/Women/Clothing/Coats': 92,
  'Fashion/Women/Clothing/Coats/Double Breasted & Peacoats': 93,
  'Fashion/Women/Clothing/Tailoring/Trouser Suits': 94,
  'Fashion/Women/Shoes/Sandals': 95,
  'Fashion/Women/Clothing/Coats/Leather Coats': 96,
  'Fashion/Women/Accessories/Bridal Accessories': 97,
  'Fashion/Men/Underwear & Socks/Briefs & Boxers': 98,
  'Fashion/Men/Accessories/Phone Cases & Technology': 99,
  'Fashion/Men/Clothing/Pants/Drop Crotch Pants': 100,
  'Fashion/Men/Clothing/Jackets/Suit & Dinner Jackets': 101,
  'Fashion/Men/Clothing/Suits/Tuxedos & Dinner Suits': 102,
  'Fashion/Men/Activewear/Performance Footwear': 103,
  'Fashion/Women/Fine Jewelry': 104,
  'Fashion/Women/Fine Jewelry/Fine Brooches & Pins': 105,
  'Fashion/Women/Activewear/Performance Shorts': 106,
  'Fashion/Women/Activewear/Performance Shorts/Compression Shorts': 107,
  'Fashion/Men/Shoes/Brogues': 108,
  'Fashion/Men/Watches/Fine Watches/Dress Watches': 109,
  'Fashion/Women/Clothing/Beachwear/Bikinis': 110,
  'Fashion/Men/Shoes/Loafers': 111,
  'Fashion/Men/Clothing/Shorts/Denim Shorts': 112,
  'Fashion/Women/Demi-Fine Jewelry': 113,
  'Fashion/Women/Homeware/Stationery/Pens & Pencils': 114,
  'Fashion/Men/Activewear/Surf & Swimwear': 115,
  'Fashion/Women/Clothing/Knits/Knitted Tops': 116,
  'Fashion/Women/Shoes/Mules': 117,
  'Fashion/Women/Activewear/Performance Accessories/Gym Bags': 118,
  'Fashion/Men/Clothing/Denim': 119,
  'Fashion/Men/Clothing/Denim/Regular & Straight-Leg Jeans': 120,
  'Fashion/Women/Activewear/Performance Tops/Performance T-Shirts': 121,
  'Fashion/Men/Accessories/Sunglasses': 122,
  'Fashion/Women/Homeware/Dining & Kitchen': 123,
  'Fashion/Women/Homeware/Dining & Kitchen/Glassware': 124,
  'Fashion/Men/Accessories/Pets accessories': 125,
  'Fashion/Men/Bags/Laptop Bags & Briefcases': 126,
  'Fashion/Women/Clothing/Denim/Skinny Jeans': 127,
  'Fashion/Women/Bags/Bag Accessories': 128,
  'Fashion/Men/Activewear/Performance Tops': 129,
  'Fashion/Men/Activewear/Performance Tops/Cycling Tops': 130,
  'Fashion/Men/Clothing/Swimwear/Swim & Board Shorts': 131,
  'Fashion/Women/Activewear/Performance Shorts/Cycling Shorts': 132,
  'Fashion/Women/Fine Jewelry/Fine Watches': 133,
  'Fashion/Women/Pre-Owned': 134,
  'Fashion/Women/Pre-Owned/Pre-Owned Jewelry': 135,
  'Fashion/Women/Lingerie & Nightwear/Nightwear/Pyjama Bottoms': 136,
  'Fashion/Men/Clothing/Jackets/Waistcoats & Gilets': 137,
  'Fashion/Women/Clothing/Jackets': 138,
  'Fashion/Women/Clothing/Jackets/Waistcoats & Gilets': 139,
  'Fashion/Men/Watches/Fashion Watches': 140,
  'Fashion/Men/Clothing/Coats/Duffle Coats': 141,
  'Fashion/Women/Clothing/Jackets/Blazers': 142,
  'Fashion/Men/Pre-Owned': 143,
  'Fashion/Men/Pre-Owned/Pre-Owned Bags': 144,
  'Fashion/Women/Clothing/Pants': 145,
  'Fashion/Women/Clothing/Pants/Sweatpants': 146,
  'Fashion/Women/Homeware/Pet Accessories': 147,
  'Fashion/Men/Homeware/Pet Accessories': 148,
  'Fashion/Women/Demi-Fine Jewelry/Demi-Fine Rings': 149,
  'Fashion/Men/Clothing/Jackets/Shirt Jackets': 150,
  'Fashion/Men/Homeware/Soft Furnishings & Textiles': 151,
  'Fashion/Men/Homeware/Soft Furnishings & Textiles/Bedding': 152,
  'Fashion/Men/Shoes/Monk Shoes': 153,
  'Fashion/Women/Bags/Clutch Bags': 154,
  'Fashion/Men/Clothing/Jackets/Sport Jackets & Windbreakers': 155,
  'Fashion/Women/Clothing/Denim/Jean Shorts': 156,
  'Fashion/Men/Activewear/Performance Accessories/Gym Bags': 157,
  'Fashion/Women/Clothing/Skirts/Pencil Skirts': 158,
  'Fashion/Women/Bags/Shoulder Bags': 159,
  'Fashion/Men/Clothing/Jackets/Hooded Jackets': 160,
  'Fashion/Men/Activewear/Performance Shorts': 161,
  'Fashion/Men/Activewear/Performance Shorts/Cycling Shorts': 162,
  'Fashion/Women/Lingerie & Nightwear/Pantyhose & Stockings': 163,
  'Fashion/Women/Clothing/Denim/Denim Leggings': 164,
  'Fashion/Men/Watches/Watch Accessories': 165,
  'Fashion/Men/Watches/Watch Accessories/Watch Boxes': 166,
  'Fashion/Women/Fine Jewelry/Fine Earrings': 167,
  'Fashion/Women/Clothing/Dresses': 168,
  'Fashion/Women/Clothing/Dresses/Sundresses': 169,
  'Fashion/Men/Clothing/Swimwear/Beach Accessories': 170,
  'Fashion/Men/Clothing/Denim/Relaxed-Fit Jeans': 171,
  'Fashion/Men/Clothing/Denim/Slim-Fit Jeans': 172,
  'Fashion/Men/Clothing/Jumpsuits': 173,
  'Fashion/Women/Clothing/Beachwear/Beach Dresses': 174,
  'Fashion/Women/Clothing/Skirts/Asymmetric & Draped Skirts': 175,
  'Fashion/Men/Jewelry': 176,
  'Fashion/Men/Jewelry/Fine Bracelets': 177,
  'Fashion/Women/Accessories/Hair Accessories': 178,
  'Fashion/Men/Accessories/Toiletry Bags': 179,
  'Fashion/Women/Activewear/Skiwear': 180,
  'Fashion/Women/Jewelry/Body Jewelry': 181,
  'Fashion/Women/Clothing/Tops': 182,
  'Fashion/Women/Clothing/Tops/Tunic Tops & Kaftans': 183,
  'Fashion/Men/Activewear/Performance Accessories/Helmets': 184,
  'Fashion/Men/Clothing/Coats/Leather Coats': 185,
  'Fashion/Women/Clothing/Skirts/Full Skirts': 186,
  'Fashion/Men/Clothing/Sweatshirts & Knitwear': 187,
  'Fashion/Men/Clothing/Sweatshirts & Knitwear/Sweatshirts': 188,
  'Fashion/Women/Clothing/Denim/Flares & Bell Bottom Jeans': 189,
  'Fashion/Women/Accessories/Umbrellas': 190,
  'Fashion/Women/Clothing/Shorts': 191,
  'Fashion/Women/Clothing/Shorts/Tailored Shorts': 192,
  'Fashion/Women/Activewear/Skiwear/Ski Accessories': 193,
  'Fashion/Men/Activewear/Performance Footwear/Performance Trainers': 194,
  'Fashion/Women/Activewear/Performance Jackets': 195,
  'Fashion/Women/Activewear/Performance Jackets/Lightweight Jackets': 196,
  'Fashion/Men/Accessories/Gloves': 197,
  'Fashion/Women/Jewelry/Watches': 198,
  'Fashion/Men/Jewelry/Bracelets': 199,
  'Fashion/Men/Accessories/Face Masks': 200,
  'Fashion/Men/Watches/Fine Watches/Sports Watches': 201,
  'Fashion/Women/Lingerie & Nightwear/Bras': 202,
  'Fashion/Men/Bags/Luggage & Holdalls': 203,
  'Fashion/Women/Activewear/Performance Tops/Performance Sweatshirts & Hoodies': 204,
  'Fashion/Women/Activewear/Performance Trousers': 205,
  'Fashion/Women/Activewear/Performance Trousers/Performance Track Pants': 206,
  'Fashion/Women/Clothing/Jackets/Denim Jackets': 207,
  'Fashion/Men/Clothing/Shirts': 208,
  'Fashion/Women/Activewear/Performance Tops/Performance Tank Tops': 209,
  'Fashion/Men/Homeware/Dining & Kitchen/Glassware': 210,
  'Fashion/Women/Clothing/Denim/Tapered Jeans': 211,
  'Fashion/Women/Demi-Fine Jewelry/Demi-Fine Necklaces': 212,
  'Fashion/Women/Clothing/Knits/Knitted Skirts': 213,
  'Fashion/Women/Clothing/Pants/Wide-Leg Pants': 214,
  'Fashion/Women/Pre-Owned/Pre-Owned Fine Watches': 215,
  'Fashion/Women/Activewear/Performance Jackets/Performance Gilets': 216,
  'Fashion/Women/Accessories/Braces': 217,
  'Fashion/Men/Watches/Watch Accessories/Watch Straps': 218,
  'Fashion/Men/Activewear/Performance Trousers': 219,
  'Fashion/Men/Activewear/Performance Trousers/Performance Leggings': 220,
  'Fashion/Men/Clothing/T-Shirts & Vests': 221,
  'Fashion/Men/Homeware/Home Decor': 222,
  'Fashion/Women/Activewear/Performance Tops/Compression Tops': 223,
  'Fashion/Women/Clothing/Coats/Parkas': 224,
  'Fashion/Women/Clothing/Dresses/Cocktail & Party Dresses': 225,
  'Fashion/Women/Clothing/Pants/Leggings': 226,
  'Fashion/Men/Clothing/Coats/Parkas': 227,
  'Fashion/Women/Homeware/Soft Furnishings & Textiles': 228,
  'Fashion/Men/Bags/Clutch Bags': 229,
  'Fashion/Men/Accessories/Braces': 230,
  'Fashion/Men/Clothing/T-Shirts & Vests/Vests & Tank Tops': 231,
  'Fashion/Men/Jewelry/Rings': 232,
  'Fashion/Women/Accessories/Make Up Bags': 233,
  'Fashion/Men/Activewear/Performance Footwear/Performance Boots': 234,
  'Fashion/Men/Bags/Belt Bags': 235,
  'Fashion/Men/Shoes/Espadrilles': 236,
  'Fashion/Women/Shoes/Pumps': 237,
  'Fashion/Men/Activewear/Performance Accessories/Equipment': 238,
  'Fashion/Women/Activewear/Skiwear/Ski Jackets': 239,
  'Fashion/Women/Accessories/Travel Accessories': 240,
  'Fashion/Women/Clothing/Skirts/Straight Skirts': 241,
  'Fashion/Women/Clothing/Denim/Cropped Jeans': 242,
  'Fashion/Women/Lingerie & Nightwear/Camisoles & Corsets': 243,
  'Fashion/Men/Activewear/Skiwear/Ski Tops': 244,
  'Fashion/Women/Clothing/Beachwear/Beach Cover-Ups': 245,
  'Fashion/Men/Clothing/Denim/Bootcut Jeans': 246,
  'Fashion/Women/Activewear/Performance Tops/Sports Bras': 247,
  'Fashion/Women/Demi-Fine Jewelry/Demi-Fine Body Jewelry': 248,
  'Fashion/Women/Pre-Owned/Pre-Owned Bags': 249,
  'Fashion/Men/Clothing/Denim/Drop-Crotch Jeans': 250,
  'Fashion/Women/Clothing/Tops/T-Shirts & Jersey Shirts': 251,
  'Fashion/Women/Clothing/Knits/Sweater Dresses': 252,
  'Fashion/Men/Accessories/Belts': 253,
  'Fashion/Men/Clothing/Suits/Double  Breasted Suits': 254,
  'Fashion/Men/Clothing/Pants/Regular-Fit & Straight Leg Pants': 255,
  'Fashion/Men/Clothing/T-Shirts & Vests/T-Shirts': 256,
  'Fashion/Men/Accessories/Ties & Bow Ties': 257,
  'Fashion/Men/Clothing/Pants/Tailored Pants': 258,
  'Fashion/Men/Activewear/Performance Jackets/Lightweight Jackets': 259,
  'Fashion/Women/Clothing/Denim/Wide-Leg Jeans': 260,
  'Fashion/Women/Activewear/Skiwear/Ski Tops': 261,
  'Fashion/Men/Underwear & Socks/Sleepwear': 262,
  'Fashion/Men/Accessories/Scarves': 263,
  'Fashion/Women/Activewear/Performance Footwear': 264,
  'Fashion/Women/Activewear/Performance Footwear/Performance Trainers': 265,
  'Fashion/Men/Activewear/Performance Tops/Performance Sweatshirts & Hoodies': 266,
  'Fashion/Women/Clothing/Pants/Straight-Leg Pants': 267,
  'Fashion/Women/Clothing/Shorts/Knee-Length Shorts': 268,
  'Fashion/Men/Homeware/Stationery': 269,
  'Fashion/Men/Homeware/Stationery/Pens & Pencils': 270,
  'Fashion/Men/Clothing/Jackets/Leather Jackets': 271,
  'Fashion/Women/Accessories/Glasses & Frames': 272,
  'Fashion/Women/Shoes/Brogues & Oxfords': 273,
  'Fashion/Women/Shoes/Boots': 274,
  'Fashion/Men/Activewear/Performance Shorts/Compression Shorts': 275,
  'Fashion/Women/Clothing/Pants/Cropped Pants': 276,
  'Fashion/Women/Jewelry/Rings': 277,
  'Fashion/Men/Accessories/Helmets': 278,
  'Fashion/Men/Homeware/Home Decor/Decorative Trays & Plates': 279,
  'Fashion/Men/Clothing/Shorts/Drop-Crotch Shorts': 280,
  'Fashion/Women/Clothing/Pants/Slim Pants': 281,
  'Fashion/Men/Clothing/Coats/Peacoats': 282,
  'Fashion/Men/Shoes/Derby Shoes': 283,
  'Fashion/Men/Clothing/Pants/Skinny Pants': 284,
  'Fashion/Men/Jewelry/Fine Earrings': 285,
  'Fashion/Women/Fine Jewelry/Fine Necklaces': 286,
  'Fashion/Men/Clothing/Pants/Loose Fit Pants': 287,
  'Fashion/Women/Lingerie & Nightwear/Nightwear/Slips & Camisoles': 288,
  'Fashion/Men/Activewear/Performance Tops/Performance T-Shirts & Vests': 289,
  'Fashion/Women/Clothing/Rompers': 290,
  'Fashion/Women/Clothing/Rompers/Full Length': 291,
  'Fashion/Men/Clothing/Denim/Skinny Jeans': 292,
  'Fashion/Women/Pre-Owned/Pre-Owned Fine Jewelry': 293,
  'Fashion/Men/Clothing/Coats/Single Breasted Coats': 294,
  'Fashion/Women/Fine Jewelry/Fine Bracelets': 295,
  'Fashion/Men/Clothing/Shorts/Khaki Shorts': 296,
  'Fashion/Women/Activewear/Skiwear/Base Layers': 297,
  'Fashion/Women/Homeware/Soft Furnishings & Textiles/Towels & Bath Robes': 298,
  'Fashion/Women/Accessories/Gloves': 299,
  'Fashion/Men/Accessories/Wallets & Billfolds': 300,
  'Fashion/Women/Clothing/Jackets/Fitted Jackets': 301,
  'Fashion/Men/Shoes/Slippers': 302,
  'Fashion/Men/Clothing/Jackets/Blazers': 303,
  'Fashion/Men/Underwear & Socks/Loungewear': 304,
  'Fashion/Women/Pre-Owned/Pre-Owned Accessories': 305,
  'Fashion/Women/Shoes/Sneakers': 306,
  'Fashion/Women/Clothing/Tops/Vests & Tank Tops': 307,
  'Fashion/Kids': 308,
  'Fashion/Women/Clothing/Dresses/Bridal Dresses': 309,
  'Fashion/Men/Clothing/Pants/Tapered Pants': 310,
  'Fashion/Women/Fine Jewelry/Fine Body Jewelry': 311,
  'Fashion/Women/Clothing/Tops/Cardigans': 312,
  'Fashion/Men/Jewelry/Brooches & Pins': 313,
  'Fashion/Men/Clothing/Sweatshirts & Knitwear/Cardigans': 314,
  'Fashion/Women/Activewear/Performance Accessories/Hats & Caps': 315,
  'Fashion/Women/Pre-Owned/Pre-Owned Fine Watches/Pre-Owned Dress Watches': 316,
  'Fashion/Women/Clothing/Dresses/Day Dresses': 317,
  'Fashion/Men/Accessories/Glasses & Frames': 318,
  'Fashion/Women/Clothing/Coats/Capes': 319,
  'Fashion/Men/Jewelry/Fine Necklaces': 320,
  'Fashion/Women/Lingerie & Nightwear/Shapewear': 321,
  'Fashion/Men/Clothing/Coats/Double Breasted Coats': 322,
  'Fashion/Women/Clothing/Jackets/Varsity Jackets': 323,
  'Fashion/Men/Watches/Fine Watches/Chronograph Watches': 324,
  'Fashion/Women/Clothing/Skirts/A-Line Skirts': 325,
  'Fashion/Men/Clothing/Pants/Chinos': 326,
  'Fashion/Women/Clothing/Beachwear/Beach Accessories': 327,
  'Fashion/Women/Clothing/Coats/Military Coats': 328,
  'Fashion/Men/Bags/Backpacks': 329,
  'Fashion/Women/Lingerie & Nightwear/Nightwear/Pyjama Sets': 330,
  'Fashion/Men/Homeware/Soft Furnishings & Textiles/Towels & Bath Robes': 331,
  'Fashion/Men/Clothing/Pants/Legging': 332,
  'Fashion/Women/Clothing/Tailoring/Suit Jackets': 333,
  'Fashion/Men/Clothing/Jackets/Down Jackets': 334,
  'Fashion/Women/Clothing/Jackets/Cropped Jackets': 335,
  'Fashion/Women/Lingerie & Nightwear/Lingerie Accessories': 336,
  'Fashion/Women/Activewear/Performance Trousers/Performance Leggings': 337,
  'Fashion/Men/Activewear/Performance Trousers/Performance Track Pants': 338,
  'Fashion/Women/Clothing/Pants/Skinny Pants': 339,
  'Fashion/Women/Clothing/Rompers/Playsuits': 340,
  'Fashion/Women/Clothing/Coats/Single Breasted Coats': 341,
  'Fashion/Men/Clothing/Denim/Wide-Leg Jeans': 342,
  'Fashion/Men/Clothing/Denim/Cropped Jeans': 343,
  'Fashion/Women/Clothing/Jackets/Military Jackets': 344,
  'Fashion/Women/Clothing/Denim/Denim Jackets': 345,
  'Fashion/Women/Accessories/Sunglasses': 346,
  'Fashion/Women/Activewear/Skiwear/Ski All-In-One': 347,
  'Fashion/Men/Activewear/Performance Shorts/Running Shorts': 348,
  'Fashion/Men/Pre-Owned/Fine Vintage Jewelry': 349,
  'Fashion/Women/Jewelry/Bracelets': 350,
  'Fashion/Women/Clothing/Skirts/Fitted Skirts': 351,
  'Fashion/Women/Activewear/Performance Tops/Cycling Tops': 352,
  'Fashion/Women/Accessories/Phone Cases & Technology': 353,
  'Fashion/Men/Watches/Fine Watches/Diving Watches': 354,
  'Fashion/Women/Activewear/Performance Footwear/Snow Boots': 355,
  'Fashion/Women/Clothing/Coats/Faux Fur & Shearling Coats': 356,
  'Fashion/Women/Activewear/Performance Jackets/Performance Track Jackets': 357,
  'Fashion/Men/Watches/Fine Watches/Smartwatches': 358,
  'Fashion/Men/Clothing/Jackets/Denim Jackets': 359,
  'Fashion/Women/Accessories/Hats': 360,
  'Fashion/Men/Clothing/Coats/Trench Coats ': 361,
  'Fashion/Women/Clothing/Jackets/Biker Jackets': 362,
  'Fashion/Men/Jewelry/Earrings': 363,
  'Fashion/Women/Clothing/Tops/Shirts': 364,
  'Fashion/Women/Homeware/Soft Furnishings & Textiles/Bedding': 365,
  'Fashion/Women/Shoes/Flip Flops & Slides': 366,
  'Fashion/Women/Clothing/Jackets/Faux Fur & Shearling Jackets': 367,
  'Fashion/Women/Shoes/Ballerina Shoes': 368,
  'Fashion/Women/Fine Jewelry/Fine Rings': 369,
  'Fashion/Women/Clothing/Jackets/Tweed Jackets': 370,
  'Fashion/Men/Shoes/Oxford Shoes': 371,
  'Fashion/Men/Bags/Messenger Bags': 372,
  'Fashion/Women/Clothing/Pants/High Waisted Pants': 373,
  'Fashion/Men/Jewelry/Cufflinks': 374,
  'Fashion/Women/Clothing/Tops/Hoodies': 375,
  'Fashion/Women/Lingerie & Nightwear/Nightwear/Nightdresses': 376,
  'Fashion/Men/Clothing/Coats/Raincoats': 377,
  'Fashion/Men/Jewelry/Fine Rings': 378,
  'Fashion/Kids/Nursery': 379,
  'Fashion/Women/Lingerie & Nightwear/Nightwear/Sleep Accessories': 380,
  'Fashion/Women/Clothing/Denim/Straight-Leg Jeans': 381,
  'Fashion/Women/Clothing/Shorts/Leather & Faux Leather Shorts': 382,
  'Fashion/Women/Bags/Belt Bags': 383,
  'Fashion/Women/Activewear/Performance Shorts/Running Shorts': 384,
  'Fashion/Men/Jewelry/Necklaces': 385,
  'Fashion/Men/Activewear/Skiwear/Ski All-In-One': 386,
  'Fashion/Women/Accessories/Keychains & Keyrings': 387,
  'Fashion/Women/Clothing/Knits/Cardigans': 388,
  'Fashion/Women/Clothing/Dresses/Evening Dresses': 389,
  'Fashion/Women/Activewear/Performance Accessories/Performance Gloves': 390,
  'Fashion/Men/Jewelry/Fine Cufflinks': 391,
  'Fashion/Men/Clothing/Suits/Single Breasted Suits': 392,
  'Fashion/Men/Activewear/Performance Jackets/Performance Gilets': 393,
  'Fashion/Women/Clothing/Shorts/Short & Mini Shorts': 394,
  'Fashion/Women/Jewelry/Brooches & Pins': 395,
  'Fashion/Women/Accessories/Neckties & Collars': 396,
  'Fashion/Men/Shoes/Boots': 397,
  'Fashion/Women/Clothing/Tailoring/Suit Skirts': 398,
  'Fashion/Men/Clothing/Denim/Tapered Jeans': 399,
  'Fashion/Women/Clothing/Coats/Trench Coats & Raincoats': 400,
  'Fashion/Women/Bags/Messenger & Crossbody Bags': 401,
  'Fashion/Men/Shoes/Boat Shoes': 402,
  'Fashion/Women/Lingerie & Nightwear/Nightwear/Pyjama Tops': 403,
  'Fashion/Women/Shoes/Slippers': 404,
  'Fashion/Women/Lingerie & Nightwear/Bodies': 405,
  'Fashion/Women/Accessories/Belts': 406,
  'Fashion/Men/Clothing/Shorts/Tailored Shorts': 407,
  'Fashion/Women/Bags/Keyrings & Chains': 408,
  'Fashion/Men/Accessories/Cufflinks': 409,
  'Fashion/Men/Accessories/Travel Accessories': 410,
  'Fashion/Women/Demi-Fine Jewelry/Demi-Fine Brooches & Pins': 411,
  'Fashion/Men/Clothing/Shorts/Cargo Shorts': 412,
  'Fashion/Women/Clothing/Jackets/Capes': 413,
  'Fashion/Women/Clothing/Jackets/Oversized Jackets': 414,
  'Fashion/Women/Clothing/Tops/Polo Tops': 415,
  'Fashion/Women/Lingerie & Nightwear/Panties': 416,
  'Fashion/Women/Activewear/Skiwear/Ski Bottoms': 417,
  'Fashion/Women/Shoes/Loafers': 418,
  'Fashion/Women/Clothing/Shorts/Short Shorts': 419,
  'Fashion/Women/Jewelry/Necklaces': 420,
  'Fashion/Men/Clothing/Sweatshirts & Knitwear/Knitted Sweaters': 421,
  'Fashion/Women/Clothing/Pants/Slacks': 422,
  'Fashion/Men/Watches/Watch Accessories/Watch Winders': 423,
  'Fashion/Women/Activewear/Swim': 424,
  'Fashion/Women/Shoes/Lace-Up Shoes': 425,
  'Fashion/Women/Clothing/Pants/Flared & Bell-Bottom Pants': 426,
  'Fashion/Men/Clothing/Suits/Suit Jackets': 427,
  'Fashion/Men/Watches/Contemporary Watches': 428,
  'Fashion/Kids/Nursery/Changing Bags': 429,
  'Fashion/Women/Demi-Fine Jewelry/Demi-Fine Bracelets': 430,
  'Fashion/Women/Clothing/Tops/Sweaters': 431,
  'Fashion/Women/Clothing/Coats/Oversized Coats': 432,
  'Fashion/Men/Activewear/Performance Accessories/Hats & Caps': 433,
  'Fashion/Women/Activewear/Performance All-In-Ones/Performance Jumpsuits': 434,
  'Fashion/Women/Accessories/Scarves': 435,
  'Fashion/Women/Clothing/Jackets/Down Jackets': 436,
  'Fashion/Men/Bags/Tote Bags': 437,
  'Fashion/Women/Bags/Bucket Bags': 438,
  'Fashion/Women/Clothing/Denim/Boyfriend Jeans': 439,
  'Fashion/Men/Clothing/Shorts/Bermuda Shorts': 440,
  'Fashion/Women/Clothing/Pants/Tapered Pants': 441,
  'Fashion/Men/Shoes/Sneakers/Low-Tops': 442,
  'Fashion/Women/Clothing/Skirts/Pleated Skirts': 443,
  'Fashion/Men/Clothing/Jackets/Bomber Jackets': 444,
  'Fashion/Women/Demi-Fine Jewelry/Demi-Fine Earrings': 445,
  'Fashion/Men/Activewear/Skiwear/Ski Bottoms': 446,
  'Fashion/Women/Clothing/Denim/Bootcut Jeans': 447,
  'Fashion/Men/Clothing/Sweatshirts & Knitwear/Hoodies': 448,
  'Fashion/Women/Accessories/Face Masks': 449,
  'Fashion/Women/Clothing/Jackets/Leather Jackets': 450,
  'Fashion/Women/Clothing/Tops/Blouses': 451,
  'Fashion/Women/Bags/Mini Bags': 452,
  'Fashion/Men/Accessories/Keychains & Keyrings': 453,
  'Fashion/Women/Activewear/Performance Accessories/Equipment': 454,
  'Fashion/Men/Bags/Keyrings & Chains': 455,
};
